spring.datasource.url=jdbc:postgresql://localhost:5432/product
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

viacep.base-url=https://viacep.com.br/ws
viacep.connect-timeout=2s
viacep.read-timeout=3s
